export type Hsk1Word = { readonly pinyin: string; readonly meaning: string };

/** HSK 1 (HSK 2.0) vocabulary with Vietnamese glosses; 这/那/哪 include their -儿 forms. */
export const hsk1Vocabulary: Readonly<Record<string, Hsk1Word>> = {
  "爱": { pinyin: "ài", meaning: "yêu, thích" },
  "八": { pinyin: "bā", meaning: "tám" },
  "爸爸": { pinyin: "bàba", meaning: "bố" },
  "杯子": { pinyin: "bēizi", meaning: "cái cốc" },
  "北京": { pinyin: "Běijīng", meaning: "Bắc Kinh" },
  "本": { pinyin: "běn", meaning: "quyển (lượng từ cho sách)" },
  "不": { pinyin: "bù", meaning: "không" },
  "不客气": { pinyin: "bú kèqi", meaning: "không có gì (đáp lại lời cảm ơn)" },
  "菜": { pinyin: "cài", meaning: "món ăn, rau" },
  "茶": { pinyin: "chá", meaning: "trà" },
  "吃": { pinyin: "chī", meaning: "ăn" },
  "出租车": { pinyin: "chūzūchē", meaning: "xe taxi" },
  "打电话": { pinyin: "dǎ diànhuà", meaning: "gọi điện thoại" },
  "大": { pinyin: "dà", meaning: "to, lớn" },
  "的": { pinyin: "de", meaning: "của (trợ từ sở hữu)" },
  "点": { pinyin: "diǎn", meaning: "giờ (khi nói giờ)" },
  "电脑": { pinyin: "diànnǎo", meaning: "máy tính" },
  "电视": { pinyin: "diànshì", meaning: "tivi" },
  "电影": { pinyin: "diànyǐng", meaning: "phim" },
  "东西": { pinyin: "dōngxi", meaning: "đồ, đồ vật" },
  "都": { pinyin: "dōu", meaning: "đều" },
  "读": { pinyin: "dú", meaning: "đọc" },
  "对不起": { pinyin: "duìbuqǐ", meaning: "xin lỗi" },
  "多": { pinyin: "duō", meaning: "nhiều; (多大) bao nhiêu" },
  "多少": { pinyin: "duōshao", meaning: "bao nhiêu" },
  "儿子": { pinyin: "érzi", meaning: "con trai" },
  "二": { pinyin: "èr", meaning: "hai" },
  "饭店": { pinyin: "fàndiàn", meaning: "nhà hàng, khách sạn" },
  "飞机": { pinyin: "fēijī", meaning: "máy bay" },
  "分钟": { pinyin: "fēnzhōng", meaning: "phút" },
  "高兴": { pinyin: "gāoxìng", meaning: "vui" },
  "个": { pinyin: "gè", meaning: "cái, người (lượng từ chung)" },
  "工作": { pinyin: "gōngzuò", meaning: "làm việc, công việc" },
  "狗": { pinyin: "gǒu", meaning: "con chó" },
  "汉语": { pinyin: "Hànyǔ", meaning: "tiếng Hán, tiếng Trung" },
  "好": { pinyin: "hǎo", meaning: "tốt, khỏe" },
  "号": { pinyin: "hào", meaning: "ngày (trong tháng), số" },
  "喝": { pinyin: "hē", meaning: "uống" },
  "和": { pinyin: "hé", meaning: "và" },
  "很": { pinyin: "hěn", meaning: "rất" },
  "后面": { pinyin: "hòumiàn", meaning: "phía sau" },
  "回": { pinyin: "huí", meaning: "về" },
  "会": { pinyin: "huì", meaning: "biết (làm gì); sẽ" },
  "火车站": { pinyin: "huǒchēzhàn", meaning: "ga tàu hỏa" },
  "几": { pinyin: "jǐ", meaning: "mấy" },
  "家": { pinyin: "jiā", meaning: "nhà, gia đình" },
  "叫": { pinyin: "jiào", meaning: "gọi; tên là" },
  "今天": { pinyin: "jīntiān", meaning: "hôm nay" },
  "九": { pinyin: "jiǔ", meaning: "chín" },
  "开": { pinyin: "kāi", meaning: "mở; lái (xe)" },
  "看": { pinyin: "kàn", meaning: "xem, nhìn, đọc" },
  "看见": { pinyin: "kànjiàn", meaning: "nhìn thấy" },
  "块": { pinyin: "kuài", meaning: "đồng (đơn vị tiền)" },
  "来": { pinyin: "lái", meaning: "đến" },
  "老师": { pinyin: "lǎoshī", meaning: "thầy giáo, cô giáo" },
  "了": { pinyin: "le", meaning: "rồi (trợ từ: đã xảy ra, đã thay đổi)" },
  "冷": { pinyin: "lěng", meaning: "lạnh" },
  "里": { pinyin: "lǐ", meaning: "trong" },
  "六": { pinyin: "liù", meaning: "sáu" },
  "妈妈": { pinyin: "māma", meaning: "mẹ" },
  "吗": { pinyin: "ma", meaning: "không? (trợ từ nghi vấn)" },
  "买": { pinyin: "mǎi", meaning: "mua" },
  "猫": { pinyin: "māo", meaning: "con mèo" },
  "没关系": { pinyin: "méi guānxi", meaning: "không sao" },
  "没有": { pinyin: "méiyǒu", meaning: "không có; chưa" },
  "米饭": { pinyin: "mǐfàn", meaning: "cơm" },
  "名字": { pinyin: "míngzi", meaning: "tên" },
  "明天": { pinyin: "míngtiān", meaning: "ngày mai" },
  "哪": { pinyin: "nǎ", meaning: "nào" },
  "哪儿": { pinyin: "nǎr", meaning: "ở đâu" },
  "那": { pinyin: "nà", meaning: "kia, đó" },
  "那儿": { pinyin: "nàr", meaning: "chỗ đó" },
  "呢": { pinyin: "ne", meaning: "trợ từ cuối câu (đang…; còn… thì sao?)" },
  "能": { pinyin: "néng", meaning: "có thể" },
  "你": { pinyin: "nǐ", meaning: "bạn, anh, chị (ngôi thứ hai)" },
  "年": { pinyin: "nián", meaning: "năm" },
  "女儿": { pinyin: "nǚ'ér", meaning: "con gái" },
  "朋友": { pinyin: "péngyou", meaning: "bạn bè" },
  "漂亮": { pinyin: "piàoliang", meaning: "đẹp" },
  "苹果": { pinyin: "píngguǒ", meaning: "quả táo" },
  "七": { pinyin: "qī", meaning: "bảy" },
  "前面": { pinyin: "qiánmiàn", meaning: "phía trước" },
  "钱": { pinyin: "qián", meaning: "tiền" },
  "请": { pinyin: "qǐng", meaning: "mời; xin" },
  "去": { pinyin: "qù", meaning: "đi" },
  "热": { pinyin: "rè", meaning: "nóng" },
  "人": { pinyin: "rén", meaning: "người" },
  "认识": { pinyin: "rènshi", meaning: "quen, quen biết" },
  "三": { pinyin: "sān", meaning: "ba" },
  "商店": { pinyin: "shāngdiàn", meaning: "cửa hàng" },
  "上": { pinyin: "shàng", meaning: "trên" },
  "上午": { pinyin: "shàngwǔ", meaning: "buổi sáng" },
  "少": { pinyin: "shǎo", meaning: "ít" },
  "谁": { pinyin: "shéi", meaning: "ai" },
  "什么": { pinyin: "shénme", meaning: "gì, cái gì" },
  "十": { pinyin: "shí", meaning: "mười" },
  "时候": { pinyin: "shíhou", meaning: "lúc; (什么时候) khi nào" },
  "是": { pinyin: "shì", meaning: "là" },
  "书": { pinyin: "shū", meaning: "sách" },
  "水": { pinyin: "shuǐ", meaning: "nước" },
  "水果": { pinyin: "shuǐguǒ", meaning: "hoa quả" },
  "睡觉": { pinyin: "shuìjiào", meaning: "ngủ" },
  "说": { pinyin: "shuō", meaning: "nói" },
  "四": { pinyin: "sì", meaning: "bốn" },
  "岁": { pinyin: "suì", meaning: "tuổi" },
  "他": { pinyin: "tā", meaning: "anh ấy, ông ấy" },
  "她": { pinyin: "tā", meaning: "cô ấy, bà ấy" },
  "太": { pinyin: "tài", meaning: "quá" },
  "天气": { pinyin: "tiānqì", meaning: "thời tiết" },
  "听": { pinyin: "tīng", meaning: "nghe" },
  "同学": { pinyin: "tóngxué", meaning: "bạn học" },
  "喂": { pinyin: "wèi", meaning: "alo (khi gọi điện)" },
  "我": { pinyin: "wǒ", meaning: "tôi" },
  "我们": { pinyin: "wǒmen", meaning: "chúng tôi, chúng ta" },
  "五": { pinyin: "wǔ", meaning: "năm (số 5)" },
  "喜欢": { pinyin: "xǐhuan", meaning: "thích" },
  "下": { pinyin: "xià", meaning: "dưới; xuống" },
  "下午": { pinyin: "xiàwǔ", meaning: "buổi chiều" },
  "下雨": { pinyin: "xià yǔ", meaning: "mưa" },
  "先生": { pinyin: "xiānsheng", meaning: "ông, ngài; chồng" },
  "现在": { pinyin: "xiànzài", meaning: "bây giờ" },
  "想": { pinyin: "xiǎng", meaning: "muốn; nghĩ, nhớ" },
  "小": { pinyin: "xiǎo", meaning: "nhỏ" },
  "小姐": { pinyin: "xiǎojiě", meaning: "cô (cách gọi phụ nữ trẻ)" },
  "些": { pinyin: "xiē", meaning: "một vài, những" },
  "写": { pinyin: "xiě", meaning: "viết" },
  "谢谢": { pinyin: "xièxie", meaning: "cảm ơn" },
  "星期": { pinyin: "xīngqī", meaning: "tuần; thứ" },
  "学生": { pinyin: "xuésheng", meaning: "học sinh" },
  "学习": { pinyin: "xuéxí", meaning: "học" },
  "学校": { pinyin: "xuéxiào", meaning: "trường học" },
  "一": { pinyin: "yī", meaning: "một" },
  "衣服": { pinyin: "yīfu", meaning: "quần áo" },
  "医生": { pinyin: "yīshēng", meaning: "bác sĩ" },
  "医院": { pinyin: "yīyuàn", meaning: "bệnh viện" },
  "椅子": { pinyin: "yǐzi", meaning: "cái ghế" },
  "有": { pinyin: "yǒu", meaning: "có" },
  "月": { pinyin: "yuè", meaning: "tháng" },
  "在": { pinyin: "zài", meaning: "ở; đang" },
  "再见": { pinyin: "zàijiàn", meaning: "tạm biệt" },
  "怎么": { pinyin: "zěnme", meaning: "thế nào, sao" },
  "怎么样": { pinyin: "zěnmeyàng", meaning: "như thế nào" },
  "这": { pinyin: "zhè", meaning: "này, đây" },
  "这儿": { pinyin: "zhèr", meaning: "ở đây" },
  "中国": { pinyin: "Zhōngguó", meaning: "Trung Quốc" },
  "中午": { pinyin: "zhōngwǔ", meaning: "buổi trưa" },
  "住": { pinyin: "zhù", meaning: "ở, sống" },
  "桌子": { pinyin: "zhuōzi", meaning: "cái bàn" },
  "字": { pinyin: "zì", meaning: "chữ" },
  "昨天": { pinyin: "zuótiān", meaning: "hôm qua" },
  "坐": { pinyin: "zuò", meaning: "ngồi; đi (xe, máy bay)" },
  "做": { pinyin: "zuò", meaning: "làm" },
};

/** Names used in the tests; not part of the HSK word count. */
export const hsk1ProperNouns: Readonly<Record<string, Hsk1Word>> = {
  "王月": { pinyin: "Wáng Yuè", meaning: "tên người (Vương Nguyệt)" },
};
